name: Build Jailbreak Tweak (Rootless)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: setup theos
      run: |
        # install theos dependencies using brew
        brew install make ldid
        
        # set PATH to use brew's GNU make
        echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH
        
        # set theos environment variables
        export THEOS=$HOME/theos
        echo "THEOS=$THEOS" >> $GITHUB_ENV
        echo "export PATH=$THEOS/bin:$PATH" >> $GITHUB_ENV
        
        # clone theos
        git clone --recursive https://github.com/theos/theos.git $THEOS
        
        # create theos configuration file
        mkdir -p $THEOS
        cat > $THEOS/theos.conf << EOF
        THEOS_PLATFORM_SDK_ROOT = $THEOS/sdks
        EOF
        
        # setup frameworks directory
        mkdir -p $THEOS/lib
        
    - name: setup ios sdk
      run: |
        export THEOS=$HOME/theos
        
        # download ios sdk using sparse checkout from official theos sdks
        git clone --quiet -n --depth=1 --filter=tree:0 https://github.com/theos/sdks/
        cd sdks
        git sparse-checkout set --no-cone iPhoneOS14.5.sdk
        git checkout
        mkdir -p $THEOS/sdks
        mv *.sdk $THEOS/sdks/
        cd ..
        rm -rf sdks
        
        # verify sdk installation
        ls -la $THEOS/sdks/
        ls -la $THEOS/sdks/iPhoneOS14.5.sdk/
        
    - name: setup frameworks
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        export THEOS_LIBRARY_PATH=$THEOS/lib
        
        # Download and setup AltList framework
        git clone --quiet --depth=1 https://github.com/opa334/AltList.git
        cd AltList
        
        # set deployment target and architecture; force arm64e and iOS 14.0+
        sed -i '' 's/^TARGET = .*$/TARGET = iphone:clang:14.5:14.0/' Makefile || true
        sed -i '' 's/^ARCHS *=.*$/ARCHS = arm64e/' Makefile || true
        
        # do not build subprojects (skip AltListTestPreferences)
        sed -i '' '/^SUBPROJECTS/d' Makefile || true
        
        # build the framework without packaging; this produces the framework in .theos/obj
        make clean all DEBUG=0 FINALPACKAGE=0 ARCHS=arm64e TARGET=iphone:clang:14.5:14.0
        
        # locate built framework and copy to Theos lib directory
        mkdir -p $THEOS/lib/Frameworks
        BUILT_FW_PATH=$(find .theos -type d -name 'AltList.framework' -print -quit)
        if [ -z "$BUILT_FW_PATH" ]; then
          echo "AltList.framework not found in build outputs" >&2
          exit 1
        fi
        cp -R "$BUILT_FW_PATH" $THEOS/lib/Frameworks/
        
        # Create symlink for backward compatibility
        ln -sf $THEOS/lib/Frameworks/AltList.framework $THEOS/lib/AltList.framework
        
        cd ..
        rm -rf AltList
        
        # Verify framework installation
        echo "Framework in lib/Frameworks:"
        ls -la $THEOS/lib/Frameworks/AltList.framework
        echo "Framework symlink in lib:"
        ls -la $THEOS/lib/AltList.framework
        
    - name: build tweak
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        export THEOS_LIBRARY_PATH=$THEOS/lib
        
        # build the main tool for rootless jailbreaks (dopamine, palera1n, etc.)
        cd $GITHUB_WORKSPACE
        make package THEOS_PACKAGE_SCHEME=rootless DEBUG=0 FINALPACKAGE=1 ARCHS=arm64e TARGET=iphone:clang:14.5:14.0
        
        # list built artifacts
        ls -la packages/
        
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: tweak-package
        path: packages/
        retention-days: 30
        
    - name: build preferences
      run: |
        export THEOS=$HOME/theos
        export PATH=$THEOS/bin:$PATH
        export THEOS_LIBRARY_PATH=$THEOS/lib
        
        cd $GITHUB_WORKSPACE/ScrubblePrefs
        make package THEOS_PACKAGE_SCHEME=rootless DEBUG=0 FINALPACKAGE=1 ARCHS=arm64e TARGET=iphone:clang:14.5:14.0
        
        # list built preference bundle
        ls -la packages/
        
    - name: upload preference artifacts
      uses: actions/upload-artifact@v4
      with:
        name: preferences-package
        path: ScrubblePrefs/packages/
        retention-days: 30